import nodemailer from "nodemailer";
import { IMeeting } from "../models/Meeting";
import { IActionItem } from "../models/ActionItem";

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function buildHtml(meeting: IMeeting, actions: IActionItem[]): string {
  const actionRows = actions
    .map(
      (a) => `<tr>
        <td style="padding:8px;border-bottom:1px solid #eee">${a.task}</td>
        <td style="padding:8px;border-bottom:1px solid #eee">${a.assignee}</td>
        <td style="padding:8px;border-bottom:1px solid #eee">${a.dueDate?.toLocaleDateString() ?? "—"}</td>
      </tr>`,
    )
    .join("");

  const decisions = meeting.decisions
    .map((d) => `<li style="margin:4px 0">${d}</li>`)
    .join("");

  return `
    <div style="font-family:sans-serif;max-width:680px;margin:auto;color:#1a1a1a">
      <h1 style="font-size:22px;border-bottom:2px solid #0066cc;padding-bottom:8px">
        Minutes of Meeting
      </h1>
      <p><strong>Meeting:</strong> ${meeting.title}</p>
      <p><strong>Date:</strong> ${new Date(meeting.date).toLocaleDateString()}</p>
      <p><strong>Participants:</strong> ${meeting.participants.map((p) => p.name).join(", ")}</p>

      <h2 style="font-size:16px;margin-top:24px">Summary</h2>
      <p>${meeting.summary}</p>

      <h2 style="font-size:16px;margin-top:24px">Key decisions</h2>
      <ul>${decisions}</ul>

      <h2 style="font-size:16px;margin-top:24px">Action items</h2>
      <table style="width:100%;border-collapse:collapse;font-size:14px">
        <thead>
          <tr style="background:#f5f5f5">
            <th style="padding:8px;text-align:left">Task</th>
            <th style="padding:8px;text-align:left">Owner</th>
            <th style="padding:8px;text-align:left">Due</th>
          </tr>
        </thead>
        <tbody>${actionRows}</tbody>
      </table>
      <p style="margin-top:32px;font-size:12px;color:#888">
        Generated by AI Meeting MOM Generator
      </p>
    </div>`;
}

export async function sendMOM(
  meeting: IMeeting,
  actions: IActionItem[],
): Promise<void> {
  const to = meeting.participants.map((p) => p.email).join(", ");
  await transporter.sendMail({
    from: `"MOM Generator" <${process.env.SMTP_USER}>`,
    to,
    subject: `MOM: ${meeting.title} — ${new Date(meeting.date).toLocaleDateString()}`,
    html: buildHtml(meeting, actions),
  });
}

// Bonus feature 1 — individual reminder email for an action item
export async function sendActionReminder(
  assigneeEmail: string,
  assigneeName: string,
  task: string,
  dueDate?: Date,
): Promise<void> {
  await transporter.sendMail({
    from: `"MOM Reminder" <${process.env.SMTP_USER}>`,
    to: assigneeEmail,
    subject: `Reminder: "${task}" is due soon`,
    html: `
      <p>Hi ${assigneeName},</p>
      <p>Just a reminder that your action item is due${dueDate ? ` on <strong>${dueDate.toLocaleDateString()}</strong>` : " soon"}:</p>
      <blockquote style="border-left:4px solid #0066cc;padding-left:12px;margin:16px 0">
        ${task}
      </blockquote>
      <p>Please update the status in the MOM portal.</p>`,
  });
}
